apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms-consumer
  template:
   metadata:
      labels:
        app: ms-consumer
   spec:
      containers:
      - name: ms-consumer
        image: mostafa2020/consumer:v5
        command:
          - sh
          - -c
          - |
           apk add curl
           export version=v1.26.1
           curl -L --remote-name-all https://dl.k8s.io//bin/linux/amd64/{kubectl}
           chmod +x kubectl
           mv kubectl /usr/local/bin/
           curl -L --remote-name https://github.com/etcd-io/etcd/releases/download/v3.5.1/etcd-v3.5.1-linux-amd64.tar.gz
           tar xzvf etcd-v3.5.1-linux-amd64.tar.gz
           mv etcd-v3.5.1-linux-amd64/etcdctl /usr/local/bin/
           ./bin/consumer "10.254.2.190"
